# Valid Tags
#  start_table_tag: 
#  end_table_tag_exp:
#  end_table_tag: 
#  skip_rows: 
#  df_drop_top_rows: 
#  df_drop_tail_rows: 
#  reset_header: 
#  widths: 
#  rename_columns:
#  convert_numerics:
#  int_columns: 
#  index_col:

mode_summary:
    start_table_tag: SUMMARIZE TRIPS BY MODE AND MARKET SEGMENT
    end_table_tag_exp: True
    end_table_tag: \' \' * 2 + \'TOTAL\'
    skip_rows: 5
    reset_header: True
    df_drop_tail_rows: 1
    widths: 
        - 8
        - 10
        - 10
        - 10
        - 10
        - 10
        - 10
        - 10
    rename_columns:
        0: market
        1: sov
        2: hov2
        3: hov3
        4: hov4
        5: transit
        6: non_motor
        7: total
    int_columns:
        - market
        - sov
        - hov2
        - hov3
        - hov4
        - transit
        - non_motor
        - total

xfer_summary: 
    start_table_tag: R E P O R T  11
    end_table_tag: \n
    skip_rows: 5
    #df_drop_top_rows: 10
    #df_drop_tail_rows: 1
    reset_header: True
    widths: 
        - 8
        - 22
        - 9
        - 22
        - 11
    rename_columns:
        0: from_station
        1: from_station_name
        2: to_station
        3: to_station_name
        4: trips
    #'convert_numerics': True,
    #int_columns: 
    #    - from_station
    #    - to_station
    #    - trips
    #index_col': 'route_group_num',

brt_access: 
    start_table_tag: SUMMARIZE BUS RAPID TRANSIT STATION ACCESS VOLUMES
    end_table_tag_exp: True
    end_table_tag: \' \' * 3 + \'TOTAL\'
    skip_rows: 4
    #df_drop_top_rows: 10
    df_drop_tail_rows: 1
    reset_header: True
    widths: 
        - 8
        - 33
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
    rename_columns:
        0: psuedo_zone
        1: station_name
        2: walk
        3: bike
        4: bus
        5: pnr
        6: knr
        7: total
    #'convert_numerics': True,
    int_columns: 
        - psuedo_zone
        - walk
        - bike
        - bus
        - pnr
        - knr
        - total
    index_col: psuedo_zone
    
brt_egress: 
    start_table_tag: SUMMARIZE BUS RAPID TRANSIT STATION EGRESS VOLUMES
    end_table_tag_exp: True
    end_table_tag: \' \' * 3 + \'TOTAL\'
    skip_rows: 4
    #df_drop_top_rows: 10
    df_drop_tail_rows: 1
    reset_header: True
    widths: 
        - 8
        - 33
        - 8
        - 8
        - 8
        - 8
        - 8
    rename_columns:
        0: psuedo_zone
        1: station_name
        2: walk
        3: bus
        4: bike
        5: drive
        6: total
    #'convert_numerics': True,
    int_columns: 
        - psuedo_zone
        - walk
        - bus
        - bike
        - drive
        - total
    index_col: psuedo_zone